// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PdfReportsGenerator.Dal;

#nullable disable

namespace PdfReportsGenerator.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231229205022_AddCreateReportTasksTable")]
    partial class AddCreateReportTasksTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PdfReportsGenerator.Dal.Entities.CreateReportTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Report")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CreateReportTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
